### PR TITLE
#472 : Backup functionality has problem on windows

### LINKED ISSUE #472: Backup functionality has problem on windows
Make a backup
Go to settings and choose "Restore from backup"
Choose a file 
Enter incorrect password few times
Enter correct password
As a result error message appears

### PR DESCRIPTION
**Pull request by ilagin**
closes #472

### CODE REVIEW

File: src/js/controllers/import.js [hunk 1]
```diff
@@ -196,28 +196,26 @@
...
-                });
               });
-            }, 100);
+            });
+          })).on('error', (err) => {
+            if (err.message === 'Invalid signature in zip file') {
+              return showError('Incorrect password or file');
+            }
+
+            return showError(err);
```
Comment (fishera123) [inline src/js/controllers/import.js]: I think you should pass here err.message no?
